name: "Project 103"
description: "FastAPI web application with red homepage"
type: "fastapi"
version: "1.0.0"

framework:
  name: "fastapi"
  version: "0.104.1"

python:
  version: "3.13"
  
entry_point: "main.py"

dependencies:
  - "fastapi==0.104.1"
  - "uvicorn[standard]==0.24.0"
  - "pydantic==2.10.3"
  - "pydantic-settings==2.6.1"
  - "python-dotenv==1.0.0"

dev_dependencies:
  - "pytest==7.4.3"
  - "pytest-asyncio==0.21.1"
  - "httpx==0.25.1"
  - "black==23.11.0"
  - "flake8==6.1.0"
  - "mypy==1.7.1"

runtime:
  host: "0.0.0.0"
  port: 8103
  reload: true

features:
  - "red_homepage"
  - "health_check"
